import type { Metadata } from "next";
import { Inter, Podkova } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const podkova = Podkova({
  subsets: ["latin"],
  variable: "--font-podkova",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${podkova.variable} ${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
